/**************************************************************************
 *                                                                        *
 *  Description: Generator Utility                                        *
 *  Website:     https://github.com/DamirDenis-Tudor/PetShop-ProiectIP    *
 *  Copyright:   (c) 2024, Damir Denis-Tudor                              *
 *                                                                        *
 *  This code and information is provided "as is" without warranty of     *
 *  any kind, either expressed or implied, including but not limited      *
 *  to the implied warranties of merchantability or fitness for a         *
 *  particular purpose. You are free to use this source code in your      *
 *  applications as long as the original copyright notice is included.    *
 *                                                                        *
 **************************************************************************/

using System.Security.Cryptography;

namespace Business.Utilities;

/// <summary>
/// Utility class for generating tokens.
/// </summary>
internal static class Generator
{
    /// <summary>
    /// Generates a random token of specified length using secure random number generator.
    /// </summary>
    /// <param name="length">Length of the token. Default is 32.</param>
    /// <returns>The generated token.</returns>
    public static string GetToken(int length = 32)
    {
        var tokenData = new byte[length];

        // Generate random bytes using a secure random number generator
        using (var rng = RandomNumberGenerator.Create())
        {
            rng.GetBytes(tokenData);
        }

        // Convert the generated bytes to a Base64 encoded string and return
        return Convert.ToBase64String(tokenData);
    }
}